export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";

export const SHOW_EDUCATION = "SHOW_EDUCATION";
export const SHOW_GUITAR = "SHOW_GUITAR";
export const SHOW_TRAVEL = "SHOW_TRAVEL";

export const SHOW_PICTURES = "SHOW_PICTURES";
export const HIDE_PICTURES = "HIDE_PICTURES";
